/*
 * Copyright 2026 Jasandeep Singh
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.trading.engine.sbe.ts;

import static com.trading.engine.sbe.ts.EmitterConstants.NL;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Objects;
import uk.co.real_logic.sbe.ir.Ir;

/**
 * Emits the TypeScript constants module ({@code build/generated-ts/constants.ts}) shared by all
 * generated decoders.
 *
 * <h2>Output shape</h2>
 *
 * Three exports:
 *
 * <ul>
 *   <li>{@code PRICE_SCALE = 100_000_000n} — fixed-point pricing scale (10^8). Prices and
 *       quantities are stored on the wire as {@code bigint × PRICE_SCALE}.
 *   <li>{@code SCHEMA_ID} — IR-derived integer literal mirroring {@code <sbe:messageSchema
 *       id=...>}.
 *   <li>{@code SCHEMA_VERSION} — IR-derived integer literal mirroring {@code <sbe:messageSchema
 *       version=...>}.
 * </ul>
 *
 * The schema-identity pair lets APP-40 (and other consumers) detect codec drift at boot without
 * reaching into a per-decoder static (e.g. compare against the server-reported schema version on
 * the first frame; refuse to decode under mismatch). Currently unused at the consumer side —
 * exported now so the contract is stable when drift detection lands without forcing a separate
 * codegen change.
 *
 * <h2>Threading model</h2>
 *
 * Not thread-safe. Build-time only.
 *
 * <h2>Allocation behavior</h2>
 *
 * Build-time only — allocates freely while constructing emitted source.
 *
 * @see TypeScriptCodeGenerator
 * @see HelpersGenerator
 */
final class ConstantsGenerator {

  /** Filename for the constants module emitted alongside per-message files. */
  static final String CONSTANTS_FILENAME = "constants.ts";

  /** Constructor — no state. */
  ConstantsGenerator() {
    // intentionally empty
  }

  /**
   * Emit {@code constants.ts} into the output directory. {@code SCHEMA_ID} / {@code SCHEMA_VERSION}
   * are read from the IR at codegen time and embedded as integer literals.
   *
   * @param ir parsed SBE intermediate representation; provides {@code id()} and {@code version()}
   * @param outputDir absolute output directory, already created by the orchestrator
   * @throws IOException if the file cannot be written
   * @throws NullPointerException if any argument is null
   */
  void generate(final Ir ir, final Path outputDir) throws IOException {
    Objects.requireNonNull(ir, "ir");
    Objects.requireNonNull(outputDir, "outputDir");

    final var sb = new StringBuilder(1_024);
    sb.append("// AUTO-GENERATED by :sbe-typescript-generator:generateTsCodecs (APP-34).")
        .append(NL)
        .append("// Workspace constants. Do not edit.")
        .append(NL)
        .append(NL)
        .append(
            "/** Fixed-point pricing scale: 10^8. Prices/quantities are `bigint * 100_000_000n`. */")
        .append(NL)
        .append("export const PRICE_SCALE = 100_000_000n;")
        .append(NL)
        .append(NL)
        .append("/**")
        .append(NL)
        .append(
            " * SBE schema identity — read-only mirror of `<sbe:messageSchema id=... version=...>`.")
        .append(NL)
        .append(" * Currently unused by APP-40 (intentional — exported for future boot-time drift")
        .append(NL)
        .append(
            " * checks: a consumer that booted against schema v1 should refuse to decode frames")
        .append(NL)
        .append(" * produced by v2). Stable contract; no codegen change required when drift")
        .append(NL)
        .append(" * detection lands.")
        .append(NL)
        .append(" */")
        .append(NL)
        // Type annotations omitted — TS infers `number` from the literal; `noImplicitAny`-clean
        // and matches the @typescript-eslint/no-inferrable-types convention (also matches
        // PRICE_SCALE above which omits the redundant `: bigint`).
        .append("export const SCHEMA_ID = ")
        .append(ir.id())
        .append(";")
        .append(NL)
        .append("export const SCHEMA_VERSION = ")
        .append(ir.version())
        .append(";")
        .append(NL);
    Files.writeString(outputDir.resolve(CONSTANTS_FILENAME), sb, StandardCharsets.UTF_8);
  }
}
