/*
 * Copyright 2026 Jasandeep Singh
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.trading.engine.sbe.ts;

import static com.trading.engine.sbe.ts.EmitterConstants.NL;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import uk.co.real_logic.sbe.PrimitiveType;
import uk.co.real_logic.sbe.ir.HeaderStructure;
import uk.co.real_logic.sbe.ir.Ir;
import uk.co.real_logic.sbe.ir.Signal;

/**
 * Emits {@code messageHeader.ts} — a {@code DataView}-flyweight TypeScript decoder for SBE's fixed
 * message header.
 *
 * <h2>Output shape</h2>
 *
 * One file per build: {@code <outputDir>/messageHeader.ts}. The emitted module exports a single
 * {@code MessageHeaderDecoder} class with {@code wrap(buffer, offset)} plus one accessor per header
 * field (typically {@code blockLength}, {@code templateId}, {@code schemaId}, {@code version} — all
 * {@code uint16} per SBE's {@code messageHeader} composite). Every getter reads via {@link
 * java.nio.ByteBuffer}-equivalent {@code DataView} primitives passing {@code littleEndian = true},
 * matching {@code trading-schema.xml}'s {@code byteOrder="littleEndian"} declaration.
 *
 * <h2>Threading model</h2>
 *
 * Not thread-safe. Build-time only. Each {@link #generate(Ir, Path)} invocation runs single-
 * threaded inside the SBE-tool JVM.
 *
 * <h2>Allocation behavior</h2>
 *
 * Build-time only — allocates freely while constructing the emitted source.
 *
 * <h2>Design rationale</h2>
 *
 * The message header is the fixed prefix preceding every SBE message; consumers MUST decode it
 * first to find the {@code templateId} (which selects the per-message decoder) and the {@code
 * blockLength} (which delimits the root field block before any repeating groups). Emitting a single
 * shared {@code messageHeader.ts} (rather than inlining accessors into every per-message file)
 * keeps the generated tree small and allows downstream Vite/Vitest tree-shaking to drop the decoder
 * when it isn't reachable from a consumer's named imports.
 *
 * @see TypeScriptTargetCodeGenerator
 */
final class HeaderGenerator {

  /** Filename emitted into the output directory. */
  static final String OUTPUT_FILENAME = "messageHeader.ts";

  /**
   * Emit {@code messageHeader.ts} into {@code outputDir}.
   *
   * @param ir parsed SBE intermediate representation; must not be {@code null}. The IR's {@link
   *     Ir#headerStructure()} provides the header composite definition this emitter decodes
   * @param outputDir absolute output directory, already created by the caller; must not be {@code
   *     null}
   * @throws IOException if the file cannot be written
   * @throws IllegalStateException if the schema declares a header composite this emitter does not
   *     support (non-{@code uint} primitive types or non-power-of-two widths)
   */
  void generate(final Ir ir, final Path outputDir) throws IOException {
    Objects.requireNonNull(ir, "ir");
    Objects.requireNonNull(outputDir, "outputDir");

    final var header = ir.headerStructure();
    final var fields = collectHeaderFields(header);
    final int totalLength = computeBlockLength(fields);

    final var sb = new StringBuilder(2_048);
    sb.append("// AUTO-GENERATED by :sbe-typescript-generator:generateTsCodecs (APP-34).")
        .append(NL)
        .append("// Source: ")
        .append(header.tokens().get(0).name())
        .append(" composite (id=")
        .append(ir.id())
        .append(", version=")
        .append(ir.version())
        .append("). Do not edit.")
        .append(NL)
        .append("//")
        .append(NL)
        .append("// SBE messageHeader decoder — fixed-length, DataView flyweight,")
        .append(NL)
        .append("// little-endian (matches trading-schema.xml byteOrder).")
        .append(NL)
        .append(NL)
        .append("export class MessageHeaderDecoder {")
        .append(NL)
        .append("  private buffer!: DataView;")
        .append(NL)
        .append("  private bufferOffset = 0;")
        .append(NL)
        .append(NL)
        .append("  static readonly ENCODED_LENGTH = ")
        .append(totalLength)
        .append(";")
        .append(NL)
        .append(NL)
        .append("  wrap(buffer: DataView, offset: number): this {")
        .append(NL)
        .append("    this.buffer = buffer;")
        .append(NL)
        .append("    this.bufferOffset = offset;")
        .append(NL)
        .append("    return this;")
        .append(NL)
        .append("  }")
        .append(NL);

    for (final var field : fields) {
      sb.append(NL).append(emitGetter(field));
    }

    sb.append("}").append(NL);

    Files.writeString(outputDir.resolve(OUTPUT_FILENAME), sb, StandardCharsets.UTF_8);
  }

  /**
   * Collect the header's flat field list. The header composite is a sequence of primitive fields;
   * for SBE's standard {@code messageHeader} this yields four {@code uint16} fields (blockLength,
   * templateId, schemaId, version) but the emitter accepts whatever the schema declares.
   */
  private static List<HeaderField> collectHeaderFields(final HeaderStructure header) {
    final var tokens = header.tokens();
    // The first token is BEGIN_COMPOSITE for messageHeader; the last is END_COMPOSITE. Each
    // intermediate ENCODING token is a primitive field. SBE always lays them out
    // sequentially, so token offsets match emitted struct offsets.
    final var fields = new ArrayList<HeaderField>(tokens.size());
    int offset = 0;
    for (final var token : tokens) {
      if (token.signal() != Signal.ENCODING) {
        continue;
      }
      final var primitive = token.encoding().primitiveType();
      requireSupportedPrimitive(token.name(), primitive);
      final int width = primitive.size();
      fields.add(new HeaderField(token.name(), primitive, offset, width));
      offset += width;
    }
    return List.copyOf(fields);
  }

  private static int computeBlockLength(final List<HeaderField> fields) {
    int total = 0;
    for (final var field : fields) {
      total += field.width();
    }
    return total;
  }

  /**
   * Reject header field types we don't currently support. The standard SBE messageHeader uses only
   * unsigned integer primitives; if a schema introduces a signed or non-power-of-two width (which
   * the spec does not actually permit for the header), surface it loudly rather than emitting
   * silently broken decoders.
   */
  private static void requireSupportedPrimitive(final String name, final PrimitiveType type) {
    switch (type) {
      case UINT8, UINT16, UINT32, UINT64 -> {
        // supported
      }
      default ->
          throw new IllegalStateException(
              "Unsupported header primitive type for field '"
                  + name
                  + "': "
                  + type
                  + " (SBE messageHeader composites are expected to be unsigned integers only)");
    }
  }

  private static String emitGetter(final HeaderField field) {
    final var sb = new StringBuilder(192);
    final var dataViewMethod =
        switch (field.primitive()) {
          case UINT8 -> "getUint8";
          case UINT16 -> "getUint16";
          case UINT32 -> "getUint32";
          case UINT64 -> "getBigUint64";
          default ->
              throw new IllegalStateException(
                  "Unreachable: requireSupportedPrimitive should have caught " + field.primitive());
        };
    // uint64 returns bigint per CLAUDE.md "int64/uint64 → bigint (avoids 2^53 precision loss)";
    // narrower uints fit in JS number safely.
    final var returnType = field.primitive() == PrimitiveType.UINT64 ? "bigint" : "number";
    // DataView.getUint8 takes only (byteOffset); a second arg is silently ignored per
    // ECMA-262, but emitting it implies endianness matters for a single-byte read, which is
    // misleading. Skip the trailing `, true` for single-byte primitives.
    final boolean needsEndianArg = field.primitive() != PrimitiveType.UINT8;
    sb.append("  ")
        .append(field.name())
        .append("(): ")
        .append(returnType)
        .append(" {")
        .append(NL)
        .append("    return this.buffer.")
        .append(dataViewMethod)
        .append("(this.bufferOffset + ")
        .append(field.offset())
        .append(needsEndianArg ? ", true);" : ");")
        .append(NL)
        .append("  }")
        .append(NL);
    return sb.toString();
  }

  /**
   * One field of the message header.
   *
   * @param name field name from the IR (e.g. {@code blockLength}, {@code templateId})
   * @param primitive primitive type (always one of {@code UINT8} / {@code UINT16} / {@code UINT32}
   *     / {@code UINT64} per {@link #requireSupportedPrimitive(String, PrimitiveType)})
   * @param offset byte offset within the composite, from 0
   * @param width byte width of the primitive (1, 2, 4, or 8)
   */
  private record HeaderField(String name, PrimitiveType primitive, int offset, int width) {}
}
