/*
 * Copyright 2026 Jasandeep Singh
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.trading.engine.sbe.ts;

import static com.trading.engine.sbe.ts.EmitterConstants.NL;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Objects;

/**
 * Emits the TypeScript helpers module ({@code build/generated-ts/helpers.ts}) shared by all
 * generated decoders and consumed by APP-40 directly via the {@code @trading/sbe-codecs} workspace.
 *
 * <h2>Output shape</h2>
 *
 * Three exported functions:
 *
 * <ul>
 *   <li>{@code toFixed8(b: bigint): string} — bigint micros → 8-fractional-digit decimal string, no
 *       trailing-zero trim. Pure formatter; used by render-edge code that surfaces fixed-point
 *       prices to humans.
 *   <li>{@code parseFixed8(decimalString: string): bigint} — decimal string → bigint micros.
 *       Validates against {@code ^-?(0|[1-9]\d*)(\.\d{1,8})?$} (rejects leading zeros for symmetry
 *       with JSON number grammar; rejects scientific notation, NaN, Infinity, lone sign / dot,
 *       leading/trailing dot, more than 8 fractional digits). Round-trips with {@code toFixed8} for
 *       any input that {@code toFixed8} produces.
 *   <li>{@code nanosToDate(ns: bigint): Date} — bigint epoch nanos → JS {@code Date} via
 *       millisecond integer division. Render-edge only; the decoder returns bigint nanos so the
 *       full precision is preserved on the wire.
 * </ul>
 *
 * <h2>Why this is content-static</h2>
 *
 * The helpers do not depend on the SBE schema; their content is the same for every project. They
 * are emitted by the generator (rather than checked-in) because the generated tree must be a single
 * self-contained workspace consumed via {@code @trading/sbe-codecs} — checking them in elsewhere
 * would split the workspace contract across two source-of-truths. End-to-end correctness is
 * exercised through chunk-13 {@code RoundTripIT}'s {@code
 * roundTrip_quote_bidPxThroughHelpersToFixed8RoundTrips} test rather than through Java-side
 * string-match-only unit tests.
 *
 * <h2>Threading model</h2>
 *
 * Not thread-safe. Build-time only.
 *
 * <h2>Allocation behavior</h2>
 *
 * Build-time only — allocates freely while constructing emitted source.
 *
 * @see TypeScriptCodeGenerator
 * @see MessageGenerator
 */
final class HelpersGenerator {

  /** Filename for the helpers module emitted alongside per-message files. */
  static final String HELPERS_FILENAME = "helpers.ts";

  /** Constructor — no state. */
  HelpersGenerator() {
    // intentionally empty
  }

  /**
   * Emit {@code helpers.ts} into the output directory. Idempotent across builds because the output
   * is content-static.
   *
   * @param outputDir absolute output directory, already created by the orchestrator
   * @throws IOException if the file cannot be written
   * @throws NullPointerException if {@code outputDir} is null
   */
  void generate(final Path outputDir) throws IOException {
    Objects.requireNonNull(outputDir, "outputDir");
    final var sb = new StringBuilder(2_048);
    sb.append("// AUTO-GENERATED by :sbe-typescript-generator:generateTsCodecs (APP-34).")
        .append(NL)
        .append("// Helpers shared by all generated decoders. Do not edit.")
        .append(NL)
        .append(NL)
        // The regex is hoisted to a module-scope constant so the regex object is constructed
        // once at module-load time and reused on every parseFixed8 call. Avoids per-call
        // RegExp allocation on the parse hot path.
        .append("/** Validates the textual decimal grammar accepted by `parseFixed8`. */")
        .append(NL)
        .append("const FIXED8_REGEX = /^-?(0|[1-9]\\d*)(\\.\\d{1,8})?$/;")
        .append(NL)
        .append(NL)
        // toFixed8 — bigint → 8-fractional-digit decimal string; no trailing-zero trim. The
        // padStart on the fractional component is what distinguishes this from a naive
        // bigint→string conversion: it preserves leading zeros that BigInt drops, which the
        // round-trip with parseFixed8 needs.
        .append("/**")
        .append(NL)
        .append(" * Render a bigint micros value as an 8-fractional-digit decimal string.")
        .append(NL)
        .append(" * Round-trips with `parseFixed8` for any input this function produces.")
        .append(NL)
        .append(" *")
        .append(NL)
        .append(" * @param b - the bigint to render. Negative values render with a leading `-`.")
        .append(NL)
        .append(" * @returns the decimal string, e.g. `108520000n` → `\"1.08520000\"`.")
        .append(NL)
        .append(" */")
        .append(NL)
        .append("export function toFixed8(b: bigint): string {")
        .append(NL)
        .append("  const negative = b < 0n;")
        .append(NL)
        .append("  const abs = negative ? -b : b;")
        .append(NL)
        .append("  const whole = abs / 100_000_000n;")
        .append(NL)
        .append("  const frac = abs % 100_000_000n;")
        .append(NL)
        .append("  const fracStr = frac.toString().padStart(8, \"0\");")
        .append(NL)
        .append("  return (negative ? \"-\" : \"\") + whole.toString() + \".\" + fracStr;")
        .append(NL)
        .append("}")
        .append(NL)
        .append(NL)
        // parseFixed8 — strict grammar; rejects scientific notation, NaN, Infinity, leading
        // zeros in the whole part, missing leading-or-trailing digits around the decimal,
        // and more than 8 fractional digits. The grammar is locked in the parent plan.
        .append("/**")
        .append(NL)
        .append(" * Parse a decimal string into bigint micros (× 10^8 fixed point).")
        .append(NL)
        .append(" *")
        .append(NL)
        .append(
            " * Accepts: `1`, `1.0852`, `0.1`, `-1.5`, `-0`, `-0.00000001`. Rejects: scientific")
        .append(NL)
        .append(" * notation (`1e5`), NaN, Infinity, leading zeros (`01.5`), bare sign (`-`),")
        .append(NL)
        .append(
            " * lone or trailing dot (`.5`, `1.`), more than 8 fractional digits, empty string.")
        .append(NL)
        .append(" *")
        .append(NL)
        .append(" * @param decimalString - the textual input.")
        .append(NL)
        .append(" * @returns bigint micros (e.g. `\"1.0852\"` → `108_520_000n`).")
        .append(NL)
        .append(" * @throws Error if the input does not match the locked grammar.")
        .append(NL)
        .append(" */")
        .append(NL)
        .append("export function parseFixed8(decimalString: string): bigint {")
        .append(NL)
        .append("  if (!FIXED8_REGEX.test(decimalString)) {")
        .append(NL)
        .append("    throw new Error(`Invalid fixed-point decimal: ${decimalString}`);")
        .append(NL)
        .append("  }")
        .append(NL)
        .append("  const negative = decimalString.startsWith(\"-\");")
        .append(NL)
        .append("  const unsigned = negative ? decimalString.slice(1) : decimalString;")
        .append(NL)
        .append("  const dotIndex = unsigned.indexOf(\".\");")
        .append(NL)
        .append("  const whole = dotIndex < 0 ? unsigned : unsigned.slice(0, dotIndex);")
        .append(NL)
        .append("  const frac = dotIndex < 0 ? \"\" : unsigned.slice(dotIndex + 1);")
        .append(NL)
        .append("  const paddedFrac = frac.padEnd(8, \"0\");")
        .append(NL)
        // BigInt() accepts leading zeros (e.g. BigInt("000000000") === 0n) — the regex above
        // already rejected leading-zero whole parts, so any leading zeros here come from
        // padEnd("0") on the fractional component, which is correct.
        .append("  const magnitude = BigInt(whole + paddedFrac);")
        .append(NL)
        .append("  return negative ? -magnitude : magnitude;")
        .append(NL)
        .append("}")
        .append(NL)
        .append(NL)
        // nanosToDate — bigint nanos → JS Date. Integer-divides by 1_000_000n to milliseconds
        // before Number(...) so the precision loss happens deterministically (and only at the
        // ns→ms boundary — JS Date itself is millisecond-precision). Use ONLY at the render
        // edge; never round-trip through Date and back to bigint.
        .append("/**")
        .append(NL)
        .append(" * Convert bigint epoch nanoseconds to a JS `Date` (millisecond-precision).")
        .append(NL)
        .append(" * Render-edge only — Date drops the sub-millisecond precision the bigint")
        .append(NL)
        .append(" * preserved on the wire. Do not round-trip through Date.")
        .append(NL)
        .append(" *")
        .append(NL)
        .append(" * @param ns - epoch nanoseconds.")
        .append(NL)
        .append(" * @returns the matching `Date`.")
        .append(NL)
        .append(" */")
        .append(NL)
        .append("export function nanosToDate(ns: bigint): Date {")
        .append(NL)
        .append("  return new Date(Number(ns / 1_000_000n));")
        .append(NL)
        .append("}")
        .append(NL);
    Files.writeString(outputDir.resolve(HELPERS_FILENAME), sb, StandardCharsets.UTF_8);
  }
}
