/*
 * Copyright 2026 Jasandeep Singh
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.trading.engine.sbe.ts;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import uk.co.real_logic.sbe.generation.CodeGenerator;
import uk.co.real_logic.sbe.ir.Ir;

/**
 * Skeleton {@link CodeGenerator} that writes only a placeholder {@code index.ts}.
 *
 * <p>Exists to make {@code :sbe-typescript-generator:generateTsCodecs} runnable end-to-end while
 * the per-emitter classes (header, enum, message, var-data, uuid composite, router, helpers,
 * constants, barrel) are landed chunk-by-chunk under APP-34. Each subsequent chunk replaces a
 * portion of this placeholder's output with real generated content; once all emitters land, this
 * class is deleted.
 *
 * <h2>Threading model</h2>
 *
 * Not thread-safe. Build-time only.
 *
 * <h2>Allocation behavior</h2>
 *
 * Build-time only; allocation freely permitted.
 *
 * @see TypeScriptTargetCodeGenerator
 */
final class PlaceholderTypeScriptCodeGenerator implements CodeGenerator {

  /** Newline used in the emitted index.ts barrel. */
  private static final String NL = "\n";

  private final Ir ir;
  private final Path outputDir;

  /**
   * @param ir parsed SBE intermediate representation; namespace, id, and version are read inside
   *     {@link #generate()} to populate the schema-identity banner in the placeholder {@code
   *     index.ts}. Reference is retained for use by the per-emitter chunks that replace this
   *     placeholder
   * @param outputDir absolute output directory; created if missing. Caller (the SPI entry point)
   *     has already validated non-null/non-blank
   */
  PlaceholderTypeScriptCodeGenerator(final Ir ir, final String outputDir) {
    this.ir = ir;
    this.outputDir = Path.of(outputDir);
  }

  /**
   * Create the output directory, delegate per-emitter file emission, then write the transitional
   * {@code index.ts} barrel re-exporting the public symbols emitted so far.
   *
   * <p>Build-time, single-threaded; allocation freely permitted. The output directory is created if
   * missing. As subsequent APP-34 chunks land their per-emitter classes
   * (Enum/Message/VarData/Uuid/Router/Helpers/Constants), they are wired in here until chunk 11
   * replaces this method with the real {@code IndexBarrelGenerator}.
   *
   * @throws IOException if the output directory cannot be created or any emitted file cannot be
   *     written
   */
  @Override
  public void generate() throws IOException {
    Files.createDirectories(outputDir);

    // Per-emitter classes wired in progressively (chunk 3+). Each emitter writes its own
    // file(s); the placeholder is responsible for the index.ts barrel until chunk 11 lands
    // the real IndexBarrelGenerator.
    new HeaderGenerator().generate(ir, outputDir);
    final var enumNames = new EnumGenerator().generate(ir, outputDir);
    final var messageDecoderNames = new MessageGenerator().generate(ir, outputDir);
    new HelpersGenerator().generate(outputDir);

    final var indexTs = outputDir.resolve("index.ts");
    final var sb = new StringBuilder(8_192);
    sb.append("// AUTO-GENERATED by :sbe-typescript-generator:generateTsCodecs").append(NL);
    sb.append("// (APP-34 placeholder; per-emitter chunks land progressively).").append(NL);
    sb.append("//").append(NL);
    sb.append("// Schema package: ")
        .append(ir.applicableNamespace() == null ? "" : ir.applicableNamespace())
        .append(NL);
    sb.append("// Schema id     : ").append(ir.id()).append(NL);
    sb.append("// Schema version: ").append(ir.version()).append(NL);
    sb.append("//").append(NL);
    sb.append("// TODO(APP-34): replaced incrementally as per-emitter classes land.").append(NL);
    sb.append(NL);
    sb.append("export { MessageHeaderDecoder } from \"./messageHeader.js\";").append(NL);
    sb.append("export { toFixed8, parseFixed8, nanosToDate } from \"./helpers.js\";").append(NL);
    for (final var enumName : enumNames) {
      // Single value re-export covers BOTH the as-const object literal and the
      // identically-named type alias from the source module. TypeScript treats values and
      // types as separate namespaces under one name; `export { Foo }` re-exports both
      // sides. Adding a parallel `export type { Foo }` triggers TS2300 (Duplicate
      // identifier) under `verbatimModuleSyntax: true` because the type binding is then
      // exported twice. Verified via strict tsc against the generated tree.
      sb.append("export { ")
          .append(enumName)
          .append(", ")
          .append(enumName)
          .append("_NULL_VAL } from \"./")
          .append(enumName)
          .append(".js\";")
          .append(NL);
    }
    for (final var decoderName : messageDecoderNames) {
      // Decoders are concrete classes (not type aliases), so a single value re-export
      // covers both the constructor and any `instanceof`/type usages on the consumer side.
      sb.append("export { ")
          .append(decoderName)
          .append(" } from \"./")
          .append(decoderName)
          .append(".js\";")
          .append(NL);
    }
    // Explicit UTF-8 — Files.writeString defaults to UTF-8 since Java 11 but stating it
    // makes the encoding contract self-documenting and matches Aeron/exchange-core idioms.
    Files.writeString(indexTs, sb, StandardCharsets.UTF_8);
  }
}
