/*
 * Copyright 2026 Jasandeep Singh
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.trading.engine.sbe.ts;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import uk.co.real_logic.sbe.generation.CodeGenerator;
import uk.co.real_logic.sbe.ir.Ir;

/**
 * Skeleton {@link CodeGenerator} that writes only a placeholder {@code index.ts}.
 *
 * <p>Exists to make {@code :sbe-typescript-generator:generateTsCodecs} runnable end-to-end while
 * the per-emitter classes (header, enum, message, var-data, uuid composite, router, helpers,
 * constants, barrel) are landed chunk-by-chunk under APP-34. Each subsequent chunk replaces a
 * portion of this placeholder's output with real generated content; once all emitters land, this
 * class is deleted.
 *
 * <h2>Threading model</h2>
 *
 * Not thread-safe. Build-time only.
 *
 * <h2>Allocation behavior</h2>
 *
 * Build-time only; allocation freely permitted.
 *
 * @see TypeScriptTargetCodeGenerator
 */
final class PlaceholderTypeScriptCodeGenerator implements CodeGenerator {

    private final Ir ir;
    private final Path outputDir;

    /**
     * @param ir parsed SBE intermediate representation; namespace, id, and version are read
     *     inside {@link #generate()} to populate the schema-identity banner in the placeholder
     *     {@code index.ts}. Reference is retained for use by the per-emitter chunks that replace
     *     this placeholder
     * @param outputDir absolute output directory; created if missing. Caller (the SPI entry point)
     *     has already validated non-null/non-blank
     */
    PlaceholderTypeScriptCodeGenerator(final Ir ir, final String outputDir) {
        this.ir = ir;
        this.outputDir = Path.of(outputDir);
    }

    @Override
    public void generate() throws IOException {
        Files.createDirectories(outputDir);
        final var indexTs = outputDir.resolve("index.ts");
        final var content =
                """
                // AUTO-GENERATED by :sbe-typescript-generator:generateTsCodecs
                // (APP-34 placeholder; per-emitter chunks land progressively).
                //
                // Schema package: %s
                // Schema id     : %d
                // Schema version: %d
                //
                // TODO(APP-34): replaced incrementally as per-emitter classes land.
                export {};
                """
                        .formatted(
                                ir.applicableNamespace() == null ? "" : ir.applicableNamespace(),
                                ir.id(),
                                ir.version());
        // Explicit UTF-8 — Files.writeString defaults to UTF-8 since Java 11 but stating it
        // makes the encoding contract self-documenting and matches Aeron/exchange-core idioms.
        Files.writeString(indexTs, content, StandardCharsets.UTF_8);
    }
}
