/*
 * Copyright 2026 Jasandeep Singh
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.trading.engine.sbe.ts;

import static com.trading.engine.sbe.ts.EmitterConstants.NL;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Objects;
import java.util.TreeSet;

/**
 * Emits the templateId-dispatch module ({@code build/generated-ts/MessageRouter.ts}) consumed by
 * APP-40 to dispatch inbound websocket frames to the matching SBE decoder.
 *
 * <h2>Output shape</h2>
 *
 * One module exporting:
 *
 * <ul>
 *   <li>{@code type Decoder} — union of every generated decoder class type, alphabetised. Lets
 *       consumers narrow {@code DecodedFrame.decoder} via templateId without manual {@code as}
 *       casts in the common case.
 *   <li>{@code interface DecodedFrame} — header metadata + bound decoder. Returned instance is a
 *       SHARED flyweight; callers MUST consume {@code decoder} synchronously before the next call
 *       to the emitted TS {@code route()} function, otherwise the underlying flyweight is rebound
 *       under their feet.
 *   <li>{@code function route(buffer: DataView, offset: number): DecodedFrame} — reads the SBE
 *       message header at {@code offset}, looks up the matching decoder in a pre-allocated map,
 *       wraps it past the header, and populates the shared {@code DecodedFrame} flyweight.
 * </ul>
 *
 * <h2>Allocation discipline</h2>
 *
 * One {@code MessageHeaderDecoder} + one instance per templateId + one shared {@code DecodedFrame}
 * literal — all allocated at module load. ZERO allocation per {@code route()} call. Matches APP-40
 * websocket-frame dispatch volume; per-call object literals would produce gen-0 GC pressure under
 * load (matches the React/Vue/Redux dev-vs-prod allocation idiom).
 *
 * <h2>Dev-mode aliasing assertion</h2>
 *
 * Every {@code route()} call increments a {@code __generation} counter on the frame when {@code
 * NODE_ENV === "development"}. V8 / esbuild dead-code-eliminate the branch in production builds so
 * the runtime cost is zero. Consumer-side regression tests (chunk 13 {@code RoundTripIT}'s {@code
 * route_returnsSharedFlyweightThatRebindsOnNextCall}) capture the counter before a second {@code
 * route()} call and assert it advanced — locks the documented "do not retain past next call"
 * contract into a regression test rather than relying on JSDoc only.
 *
 * <h2>Sort discipline</h2>
 *
 * Decoder imports + map entries are alphabetised by class name for stable cross-build output —
 * matches the chunk-11 {@code IndexBarrelGenerator} contract so router and barrel re-exports never
 * disagree on ordering.
 *
 * <h2>Threading model</h2>
 *
 * Not thread-safe. Build-time only.
 *
 * <h2>Allocation behavior</h2>
 *
 * Build-time only — allocates freely while constructing emitted source.
 *
 * @see MessageGenerator
 * @see HeaderGenerator
 * @see TypeScriptCodeGenerator
 */
final class RouterGenerator {

  /** Filename for the router module emitted alongside per-message files. */
  static final String ROUTER_FILENAME = "MessageRouter.ts";

  /** Constructor — no state. */
  RouterGenerator() {
    // intentionally empty
  }

  /**
   * Emit {@code MessageRouter.ts} into the output directory.
   *
   * @param messageDecoderNames list of generated decoder class names returned by {@link
   *     MessageGenerator#generate}; arrives in schema-declaration order — this method sorts
   *     alphabetically for emission stability
   * @param outputDir absolute output directory, already created by the orchestrator
   * @throws IOException if the file cannot be written
   * @throws NullPointerException if any argument is null
   */
  void generate(final List<String> messageDecoderNames, final Path outputDir) throws IOException {
    Objects.requireNonNull(messageDecoderNames, "messageDecoderNames");
    Objects.requireNonNull(outputDir, "outputDir");

    // TreeSet sorts and de-dupes in one pass — defensive against a future caller that hands us
    // duplicates (which would otherwise emit duplicate `import` lines and break the TS compile).
    // Mirrors IndexBarrelGenerator's sort discipline so router and barrel never disagree.
    final var sortedNames = List.copyOf(new TreeSet<>(messageDecoderNames));

    final var sb = new StringBuilder(8_192);
    sb.append("// AUTO-GENERATED by :sbe-typescript-generator:generateTsCodecs (APP-34).")
        .append(NL)
        .append("// templateId-dispatch router. Do not edit.")
        .append(NL)
        .append(NL)
        // Imports — MessageHeaderDecoder first for grouping, then all message decoders alpha.
        .append("import { MessageHeaderDecoder } from \"./messageHeader.js\";")
        .append(NL);
    for (final var name : sortedNames) {
      sb.append("import { ")
          .append(name)
          .append(" } from \"./")
          .append(name)
          .append(".js\";")
          .append(NL);
    }
    sb.append(NL)
        // Module-init flyweights: one MessageHeaderDecoder, one decoder per templateId, one
        // DecodedFrame literal. The `decoders` map uses computed keys so TS resolves each value's
        // precise type; downstream `decoder.wrap(...)` typechecks against the union of all
        // declared decoder shapes.
        .append("const headerDecoder = new MessageHeaderDecoder();")
        .append(NL)
        .append(NL)
        .append("const decoders = {")
        .append(NL);
    for (final var name : sortedNames) {
      sb.append("  [")
          .append(name)
          .append(".TEMPLATE_ID]: new ")
          .append(name)
          .append("(),")
          .append(NL);
    }
    sb.append("} as const;").append(NL).append(NL);

    // Decoder union — generated from the alphabetised decoder list so consumers get type-narrow
    // support without manual casts. Chosen over `unknown` (Gemini medium-priority feedback) since
    // the generator already knows the full set of message decoder types at codegen time. The
    // emission has three distinct shapes pinned by separate tests:
    //   - empty (`Decoder = never;`)        — guarded explicitly below; covered by
    //     `routerGenerator_emptyDecodersEmitsNeverFallback`
    //   - single (`Decoder = X;`)           — `String.join` returns the lone element verbatim;
    //     covered by `routerGenerator_singleDecoderEmitsCleanUnion`
    //   - multi  (`Decoder = X\n  | Y…;`)   — `String.join` interpolates the `| ` separator;
    //     covered by `routerGenerator_emitsTypedDecoderUnion`
    // The empty case emits TS's `never` bottom type so the file remains syntactically valid and
    // the `decoder: Decoder | undefined` field still typechecks (`never | undefined` collapses to
    // `undefined`). With no decoders the runtime `decoders` map literal is also empty, so
    // `route()` always throws "Unknown SBE templateId" — the `Decoder` union exists purely to
    // keep downstream consumer typechecks well-formed. Without the empty guard, naive emission
    // would produce `export type Decoder =\n    ;` which is a TS syntax error.
    sb.append("/** Union of every generated decoder type — consumers narrow via `templateId`. */")
        .append(NL);
    if (sortedNames.isEmpty()) {
      sb.append("export type Decoder = never;").append(NL).append(NL);
    } else {
      final var unionMembers = String.join(NL + "  | ", sortedNames);
      sb.append("export type Decoder =")
          .append(NL)
          .append("    ")
          .append(unionMembers)
          .append(";")
          .append(NL)
          .append(NL);
    }

    // DecodedFrame interface — the shared-flyweight contract is in the JSDoc; chunk-13 test
    // greps "MUST consume" to lock the documentation forwarding through the barrel re-export.
    sb.append("/**")
        .append(NL)
        .append(" * Decoded frame envelope. The instance returned by {@link route} is a SHARED")
        .append(NL)
        .append(" * flyweight — its fields and `decoder` reference are repopulated on every")
        .append(NL)
        .append(" * call. Callers MUST consume `decoder` synchronously before the next call to")
        .append(NL)
        .append(" * `route`; retaining the reference past that point yields data corruption.")
        .append(NL)
        .append(" */")
        .append(NL)
        .append("export interface DecodedFrame {")
        .append(NL)
        .append("  templateId: number;")
        .append(NL)
        .append("  schemaId: number;")
        .append(NL)
        .append("  schemaVersion: number;")
        .append(NL)
        .append("  blockLength: number;")
        .append(NL)
        .append("  /**")
        .append(NL)
        .append(
            "   * Bound decoder — typed as the {@link Decoder} union. The union gives consumers")
        .append(NL)
        .append("   * IDE autocomplete on shared decoder methods (`wrap`, `_getBuffer`, etc.) and")
        .append(NL)
        .append("   * blocks unrelated assignments at compile time, while still requiring a manual")
        .append(NL)
        .append("   * cast for message-specific getters since all decoder shapes are structurally")
        .append(NL)
        .append("   * identical (the union members are not discriminated by a literal templateId).")
        .append(NL)
        .append("   * Narrow via the `templateId` field before invoking message-specific methods:")
        .append(NL)
        .append("   *")
        .append(NL)
        .append("   *   if (frame.templateId === QuoteDecoder.TEMPLATE_ID) {")
        .append(NL)
        .append("   *     const decoder = frame.decoder as QuoteDecoder;")
        .append(NL)
        .append("   *     // ... use decoder ...")
        .append(NL)
        .append("   *   }")
        .append(NL)
        .append("   *")
        .append(NL)
        .append(
            "   * `undefined` is the pre-first-call placeholder on the shared flyweight literal;")
        .append(NL)
        .append(
            "   * after `route` returns successfully, this field is always populated. Consumers")
        .append(NL)
        .append(
            "   * who never see the pre-first-call state can treat it as `Decoder` in practice.")
        .append(NL)
        .append("   */")
        .append(NL)
        .append("  decoder: Decoder | undefined;")
        .append(NL)
        .append("  /**")
        .append(NL)
        .append("   * Dev-mode rebind counter (incremented on every `route()` call when")
        .append(NL)
        .append("   * `NODE_ENV === \"development\"`). Production builds dead-code-eliminate")
        .append(NL)
        .append("   * the increment; consumers must NOT depend on this field outside dev")
        .append(NL)
        .append("   * regression tests.")
        .append(NL)
        .append("   */")
        .append(NL)
        .append("  __generation?: number;")
        .append(NL)
        .append("}")
        .append(NL)
        .append(NL);

    sb.append("const frame: DecodedFrame = {")
        .append(NL)
        .append("  templateId: 0,")
        .append(NL)
        .append("  schemaId: 0,")
        .append(NL)
        .append("  schemaVersion: 0,")
        .append(NL)
        .append("  blockLength: 0,")
        .append(NL)
        .append("  decoder: undefined,")
        .append(NL)
        // Omit __generation from the literal so production builds (where the dev-only increment
        // is dead-code-eliminated) ship NO __generation slot at all. The optional declaration on
        // DecodedFrame + the `?? 0` fallback in the dev-mode increment branch handles first call.
        .append("};")
        .append(NL)
        .append(NL);

    // Module-scope dev-mode flag — evaluated once at module load, then read in `route()`. With a
    // bundler `define` for `process.env.NODE_ENV` this folds to a constant boolean and the
    // entire downstream `if (__isDevelopment)` branch dead-code-eliminates. Without a bundler
    // (raw browser load), the `typeof process` short-circuit + `?.` chain prevent ReferenceError
    // and the flag resolves to `false`. Hoisting also addresses Gemini's iter-7 duplication
    // feedback (one source of truth for the predicate; see chunk-9 plan §"Dev-mode aliasing").
    sb.append("const __isDevelopment =")
        .append(NL)
        .append("  typeof process !== \"undefined\" && process.env?.NODE_ENV === \"development\";")
        .append(NL)
        .append(NL);

    sb.append("/**")
        .append(NL)
        .append(" * Read the SBE message header at `offset`, dispatch to the matching decoder,")
        .append(NL)
        .append(" * and return a SHARED flyweight populated with the decoded metadata + bound")
        .append(NL)
        .append(" * decoder. Throws `Error` for unknown templateId.")
        .append(NL)
        .append(" *")
        .append(NL)
        .append(" * Both the decoder instances and the returned `DecodedFrame` are flyweights")
        .append(NL)
        .append(" * reused across calls. Callers MUST consume `decoder` synchronously before")
        .append(NL)
        .append(" * the next invocation of `route` — retaining the reference yields corrupted")
        .append(NL)
        .append(" * reads as the underlying flyweight is rebound.")
        .append(NL)
        .append(" *")
        .append(NL)
        .append(" * Bundler contract: this module references `process.env.NODE_ENV` for a")
        .append(NL)
        .append(" * dev-mode aliasing-detection counter. Browser bundlers (Vite/esbuild/webpack)")
        .append(NL)
        .append(" * MUST replace `process.env.NODE_ENV` via `define` at build time; without that")
        .append(NL)
        .append(" * replacement, raw browser load throws `ReferenceError: process is not defined`.")
        .append(NL)
        .append(" * Vite handles this by default; esbuild via")
        .append(NL)
        .append(" * `--define:process.env.NODE_ENV='\\\"production\\\"'`.")
        .append(NL)
        .append(" */")
        .append(NL)
        .append("export function route(buffer: DataView, offset: number): DecodedFrame {")
        .append(NL)
        .append("  headerDecoder.wrap(buffer, offset);")
        .append(NL)
        .append("  const templateId = headerDecoder.templateId();")
        .append(NL)
        .append("  const decoder = decoders[templateId as keyof typeof decoders];")
        .append(NL)
        .append("  if (decoder === undefined) {")
        .append(NL)
        .append("    throw new Error(")
        .append(NL)
        .append("      `Unknown SBE templateId ${templateId} at offset ${offset} ` +")
        .append(NL)
        .append(
            "        `(schemaId=${headerDecoder.schemaId()}, schemaVersion=${headerDecoder.version()}, ` +")
        .append(NL)
        .append("        `blockLength=${headerDecoder.blockLength()}).`,")
        .append(NL)
        .append("    );")
        .append(NL)
        .append("  }")
        .append(NL)
        .append("  decoder.wrap(buffer, offset + MessageHeaderDecoder.ENCODED_LENGTH);")
        .append(NL)
        .append("  frame.templateId = templateId;")
        .append(NL)
        .append("  frame.schemaId = headerDecoder.schemaId();")
        .append(NL)
        .append("  frame.schemaVersion = headerDecoder.version();")
        .append(NL)
        .append("  frame.blockLength = headerDecoder.blockLength();")
        .append(NL)
        .append("  frame.decoder = decoder;")
        .append(NL)
        // Reference the module-scope `__isDevelopment` flag (computed once at module load, see
        // declaration above). Bundler `define` substitutes the embedded `process.env.NODE_ENV` at
        // build time so the constant folds to a boolean literal and the entire `if` block
        // dead-code-eliminates in production builds. Without a bundler, the typeof + `?.` checks
        // resolve to `false` at module load, suppressing the dev-mode increment.
        .append("  if (__isDevelopment) {")
        .append(NL)
        .append("    frame.__generation = (frame.__generation ?? 0) + 1;")
        .append(NL)
        .append("  }")
        .append(NL)
        .append("  return frame;")
        .append(NL)
        .append("}")
        .append(NL);

    Files.writeString(outputDir.resolve(ROUTER_FILENAME), sb, StandardCharsets.UTF_8);
  }
}
