/*
 * SBE TypeScript code generator (1A: stub task only).
 *
 * APP-34 (1B) replaces the implementation with a Java program that
 * reads messages/src/main/resources/trading-schema.xml and emits ~60
 * .ts files plus constants.ts / helpers.ts / index.ts. The task name
 * (`generateTsCodecs`), output directory (`build/generated-ts/`), and
 * consumer contract (npm workspace `@trading/sbe-codecs` with `main`
 * pointing at `build/generated-ts/index.ts`) are intentionally stable
 * across the 1A→1B handoff so feature branches consume the workspace
 * without churn.
 */

dependencies {
    implementation(project(":messages"))
}

val schemaXml =
    rootProject.layout.projectDirectory.file(
        "messages/src/main/resources/trading-schema.xml",
    )
val generatedTsDir = layout.buildDirectory.dir("generated-ts")

val generateTsCodecs by tasks.registering {
    group = "build"
    description =
        "Generate TypeScript decoders from trading-schema.xml (1A stub; APP-34 wires the real generator)."

    // Declared inputs/outputs make the task UP-TO-DATE on warm caches —
    // bootstrap-codecs.mjs invokes the task unconditionally and relies
    // on this caching for fast no-ops.
    inputs.file(schemaXml)
    outputs.dir(generatedTsDir)

    doLast {
        val out = generatedTsDir.get().asFile
        out.mkdirs()
        out.resolve("index.ts").writeText(
            buildString {
                appendLine(
                    "// AUTO-GENERATED by :sbe-typescript-generator:generateTsCodecs (1A stub).",
                )
                appendLine(
                    "// TODO(APP-34): replace this stub with the real SBE → TypeScript generator.",
                )
                appendLine(
                    "// Consumers: @trading/sbe-codecs npm workspace (see sbe-typescript-generator/package.json).",
                )
                appendLine("export {};")
            },
        )
    }
}
